build-app:
  image: instrumentisto/flutter
  stage: build
  script:
    - cd frontend
    - touch .env
    - flutter build apk
  tags:
    - docker
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - frontend/.dart_tool
      - frontend/build
      - frontend/android/.gradle
      - frontend/android/build

