// Docs: https://www.dbml.org/docs

// All temperature values in celsius
Table species {
  name varchar [pk]
  perfect_temperature integer
  perfect_light_per_day decimal
  perfect_humidity decimal
  perfect_moisture decimal
}

Table room {
  name varchar [pk]
  user long
}


Ref: room.user > user.id

Table room_timeseries_data {
  room long
  timestamp timestamp
  temperature integer
  brightness decimal
  humidity decimal

  indexes {
      (room, timestamp) [pk]
  }
}

Ref: room_timeseries_data.room > room.name

// One plant of the user
Table plant {
  id long [pk]
  nickname varchar
  room integer
  species varchar
}

Ref: plant.room > room.name
Ref: plant.species > species.name

Table pot_timeseries_data {
  pot long 
  timestamp timestamp
  moisture decimal

indexes {
      (pot, timestamp) [pk]
  }

}

Ref: pot_timeseries_data.pot > plant.id

Table user{
  id long [pk]
}








